services:
  application:
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - REDIS_HOST="redis"
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'